language: java

cache:
  directories:
    - $HOME/.m2

branches:
  only:
    - master
    - maven
    - hard

env:
  - PARAMS=./res/research_data/futoshiki/test_futo_7_0.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_7_0.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_7_0.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_7_0.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_7_1.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_7_1.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_7_1.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_7_1.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_7_2.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_7_2.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_7_2.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_7_2.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_8_0.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_8_0.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_8_0.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_8_0.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_8_1.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_8_1.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_8_1.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_8_1.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_8_2.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_8_2.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_8_2.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_8_2.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_9_0.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_9_0.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_9_0.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_9_0.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_9_1.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_9_1.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_9_1.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_9_1.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_9_2.txt FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_9_2.txt FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/research_data/futoshiki/test_futo_9_2.txt BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/research_data/futoshiki/test_futo_9_2.txt BACKTRACKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_1 FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_1 FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_1 BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_1 BACKTRACKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_2 FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_2 FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_2 BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_2 BACKTRACKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_3 FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_3 FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_3 BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_3 BACKTRACKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_4 FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_4 FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_4 BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_4 BACKTRACKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_5 FORWARD_CHECKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_5 FORWARD_CHECKING MOST_LIMITING
  - PARAMS=./res/test_data/sudoku/test_5 BACKTRACKING MOST_CONSTRAINED
  - PARAMS=./res/test_data/sudoku/test_5 BACKTRACKING MOST_LIMITING


prescript: "mvn clean install"

script: "java -jar target/GameSolver.jar $PARAMS"
